site_name: ✨ Numbers to Words in dbt ✨
repo_name: datnguye/dbt-translate
repo_url: https://github.com/datnguye/dbt-translate
site_url: https://www.linkedin.com/in/tuiladat/
copyright: Dat Nguyen

theme:
  name: dracula
  features:
    - content.code.copy

nav:
    - Home: index.md
    - Development:
      - nav/development/contributing-guide.md
      - nav/development/release-notes.md
    - About:
      - license.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences