site_name: ✨ Numbers to Words in dbt ✨
repo_name: datnguye/dbt-translate
repo_url: https://github.com/datnguye/dbt-translate
site_url: https://www.linkedin.com/in/tuiladat/
copyright: Dat Nguyen

theme:
  name: simple-blog
  # favicon: assets/favicon.ico
  # logo: assets/logo.png
  theme_style: light
  site_name_style: normal
  title_style: bold
  colors:
    text: black
    title: black
    primary: black
    background: white
  components:
    site_name: true
    title: true
    menu: true
    preview: true
    footer: true

nav:
    - Home: index.md
    # - Getting Started: nav/getting-started.md
    # - Setup:
    #   - nav/setup/components.md
    #   - nav/setup/colors.md
    #   - nav/setup/fonts.md
    #   - nav/setup/logo.md
    #   - nav/setup/favicon.md
    - Development:
      - nav/development/contributing-guide.md
      - nav/development/release-notes.md