name: deploy documentation site

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        sqlserver_version: ["2022"]
    container:
      image: ghcr.io/dbt-msft/dbt-sqlserver:CI-3.10-msodbc18
    services:
      sqlserver:
        image: ghcr.io/dbt-msft/dbt-sqlserver:server-${{ matrix.sqlserver_version }}
        env:
          ACCEPT_EULA: 'Y'
          SA_PASSWORD: 5atyaNadell@

    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache

      - name: Install dependencies
        run: |
          pip install dbt-sqlserver
          pip install mkdocs mkdocs-material mkdocs-minify-plugin mkdocs-simple-hooks

      - name: Build dbt docs site
        run: |
          mkdir -p ~/.dbt
          cp profiles/profiles.yml ~/.dbt/profiles.yml
          dbt deps -t sqlserver
          dbt docs generate -t sqlserver
        working-directory: integration_tests
        env:
          SQLSERVER_HOST: sqlserver
          SQLSERVER_PORT: 1433
          SQLSERVER_DATABASE: msdb
          SQLSERVER_USER: sa
          SQLSERVER_PASSWORD: 5atyaNadell@
          SQLSERVER_SCHEMA: docs

      - name: Build site
        run: |
          cp -f README.md docs/index.md
          cp -f LICENSE docs/license.md
          cp -f CONTRIBUTING.md docs/nav/development/contributing-guide.md
          mkdocs build --clean

      - name: Setup Pages
        uses: actions/configure-pages@v2

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'site'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
